spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${username}
    password: ${password}
    url: ${jdbcurl}
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database: postgresql

ftp:
  host: ${ftphost}
  port: ${ftpport}
  username: ${ftpusername}
  password: ${ftppassword}

name: test-YAML


api:
  authentication:
    url: https://dr.auth.brinks.co.id/v1.2/oauth/token
    client-id: 98c9fd49-de18-491c-88c9-f800795ed058
    client-secret: /6nW3jzFF6;Nb8.Y5m1L18pRM7iO16cIgYng
  inquiry:
    url: https://api.brinks.co.id/accpac/v1.0/inqinvno
  ar:
    url: https://api.brinks.co.id/accpac/v1.0/postinvno

statement:
  regex-common: "[cC][0-9]{2}\\S+"
  regex-list: "[cC][0-9]{8}>>>[cC][0-9]{2}[-| ][0-9]{6}"
  regex-extend: "_[0-9]{2,6}"
  regex-extend2: "[0-9]{6}-[0-9]{2,6}"
  regex-repetition: ",[0-9]{2,6}"

app:
  tax-percentage: 9

bankCode: ${bankcode}

folderPath: ${folderpath}




---
spring:
  config:
    activate:
      on-profile: prod
