spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/BankStatementSynchronizerDB
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    database: postgresql

ftp:
  host: localhost
  port: 21
  username: gede
  password: gede

name: test-YAML


api:
  authentication:
    url: http://10.193.110.70:6688/authenticate
    authorization-header: 29kweu%2shdj111[)asDehac
    vendorid: ABC
    systemid: testar
    entityid: ZCSDAT
    userid: ary
  inquiry:
    url: http://10.193.110.70:6688/inqarinv
  list:
    url: http://10.193.110.70:6688/listarbat
  ar:
    url: http://10.193.110.70:6688/addarrec

statement:
  regex-common: "[cC][0-9]{2}\\S+"
  regex-list: "[cC][0-9]{8}>>>
               [cC][0-9]{2}[-| ][0-9]{6}"
  regex-extend: "_[0-9]{2}"
  regex-repetition: ",[0-9]{2}"

app:
  tax-percentage: 20




---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: cc
    url: jdbc:postgresql://localhost:5432/BankStatementSynchronizerDB
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: postgresql

ftp:
  host: localhost
  port: 21
  username: gede
  password: gede

name: prod-YAML

api:
  authentication:
    url: http://10.193.110.70:6688/authenticate
    authorization-header: 29kweu%2shdj111[)asDehac
    vendorid: ABC
    systemid: testar
    entityid: ZCSDAT
    userid: ary
  inquiry:
    url: http://10.193.110.70:6688/inqarinv
  list:
    url: http://10.193.110.70:6688/listarbat
  ar:
    url: http://10.193.110.70:6688/addarrec


statement:
  regex-common: "[cC][0-9]{2}\\S+"
  regex-list: "[cC][0-9]{8,10}>>>[cC][0-9]{2}[-| ][0-9]{6,8}"

app:
  tax-percentage: 20

